language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "OmXQdkHY2CVqh33cVi78WB1KNd7LbbqyXWe48kcsqQqpnnZXwAjUSUpfb5hxoZr3H98vB0rLcRdDFumOBbSduM7DgrGuoTo0cUXEq4rsO4X0hfPBG8MeM1HjOgJYMUzsSCc8vi8Xy+plC4xHxPjKBK1UEAkTtiXh+5xgW/QcEtc="
    on:
      tags: true
      all_branches: true
